[[news]]
date = "2025-12"
content = "Attending AGU 2025 at New Orleans, LA. What a blast! 🎉"

[[news]]
date = "2024-10"
content = "Starting my Postdoc at West Virginia University. Let's Go! 🌄"

[[news]]
date = "2024-05"
content = "Attending UW-Madison's 2024 Spring Commencement. Walked the walk~ 💃"
