type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "Reviewer"
subtitle = "Research journals"
date = "2024-2026"
content = "Reviewed papers for SSSA Journal | Soil Research | SOIL | Plants, People, Planet | New Phytologist | Earth's Future | Nature Communications |..."

[[items]]
title = "AGU Technical Committee"
subtitle = "Soil & Critical Zone"
date = "2026"
content = "Served as the vice-chair-elect of the technical committee regarding group-activity organization and website development. More about Soil & Critical Zone TC could be found [here] (https://connect.agu.org/hydrology/about/tc-committees/soils-spcztc386)."

[[items]]
title = "Outreach Activities"
subtitle = "Soil & Critical Zone"
date = "2022-2024"
content = "Created fun and kid-friendly demonstrations of soil ecology and moisture sensors at local outreach events including Wisconsin Ag Fair, Science on the Square, Kujichagulia Juneteenth Celebration, etc."

